[default]
description = "Default permissions for the plugin"
permissions = ["allow-initialize", "allow-get-products", "allow-purchase", "allow-restore-purchases", "allow-get-purchase-history", "allow-acknowledge-purchase"]
